---
- hosts: vm-host
  roles:
    - {
        role: vm-creator,
        apt_host: http.debian.net
        # my-vm must have an entry in the inventory (see hosts file)
        # some of its variables can be defined in the inventory too
        vm_name: my-vm,
        vm_domain: example.org
        vm_volume_group: defaultvg,
        vm_root_volume_size: 10G,
        vm_swap_volume_size: 1G,
        vm_memory: 1024,
        vm_cpu: 4,
        vm_bridge: br0
    }
  vars_prompt:
    - name: vm_user_password
      prompt: "Please enter a password for current user on the newly created VM"
      private: yes
  tags:
    - vm-creation

